//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOClient.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class period_in_ATO
    {
        public int id { get; set; }
        public int id_people { get; set; }
        public System.DateTime date_in { get; set; }
        public Nullable<System.DateTime> date_out { get; set; }
        public string place { get; set; }
    
        public virtual Peoples Peoples { get; set; }
    }
}
