//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATOClient.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UBD_sertificate
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_send { get; set; }
        public string number_send { get; set; }
        public Nullable<System.DateTime> date_receive { get; set; }
        public string certificate_number { get; set; }
        public Nullable<int> id_people { get; set; }
    
        public virtual Peoples Peoples { get; set; }
    }
}
